"""ADIF generation from canonical QSO data (§11.2, NFR-072, AD-014).

ADIF is a generated interoperability artifact — never the database.  Only
non-void canonical rows are exported (NFR-072); void QSOs remain in SQLite
for audit.  Dates and times derive from the stored completion epoch so the
export is independent of the sequencer's ``HHMMSS`` display string.
"""

from __future__ import annotations

import re
import time
from collections.abc import Iterable

from .repository import QsoStatus, StoredQSO

PROGRAM_ID = "MRRC-FT8"

_SAFE_TEXT = re.compile(r"^[\x20-\x7e]*$")


def _field(name: str, value: object) -> str:
    """One ``<NAME:LEN>value`` element; rejects non-printable content."""

    text = str(value)
    if not _SAFE_TEXT.match(text):
        raise ValueError(f"ADIF field {name} holds non-printable text")
    return f"<{name}:{len(text)}>{text}"


def _format_report(report: int) -> str:
    return f"{report:+03d}"


def generate_adif(
    qsos: Iterable[StoredQSO],
    *,
    program_id: str = PROGRAM_ID,
    generated_epoch: float | None = None,
) -> str:
    """Render one ADIF document from non-void canonical QSO rows."""

    generated = time.gmtime(generated_epoch if generated_epoch is not None else time.time())
    header = (
        f"Generated by {program_id}"
        f" at {time.strftime('%Y-%m-%dT%H:%M:%SZ', generated)}\n"
        f"{_field('ADIF_VER', '3.1.4')}\n"
        f"{_field('PROGRAMID', program_id)}\n"
        f"<EOH>\n"
    )
    body: list[str] = []
    for qso in qsos:
        if qso.status is QsoStatus.VOID:
            continue  # NFR-072: export is generated from non-void records
        when = time.gmtime(qso.completed_epoch)
        fields = [
            _field("STATION_CALLSIGN", qso.my_call),
            _field("MY_GRIDSQUARE", qso.my_grid),
            _field("CALL", qso.dx_call),
        ]
        if qso.dx_grid:
            fields.append(_field("GRIDSQUARE", qso.dx_grid))
        if qso.report_sent is not None:
            fields.append(_field("RST_SENT", _format_report(qso.report_sent)))
        if qso.report_rcvd is not None:
            fields.append(_field("RST_RCVD", _format_report(qso.report_rcvd)))
        fields += [
            _field("QSO_DATE", time.strftime("%Y%m%d", when)),
            _field("TIME_ON", time.strftime("%H%M%S", when)),
            _field("MODE", qso.mode),
        ]
        if qso.freq_hz > 0:
            fields.append(_field("FREQ", f"{qso.freq_hz / 1e6:.6f}"))
        if qso.band:
            fields.append(_field("BAND", qso.band))
        body.append("".join(fields) + "<EOR>\n")
    return header + "".join(body)
