set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_Fortran_MODULE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/modules")

if(NOT _MRRC_FT8_TOOLCHAIN_FLAGS_APPENDED)
  string(APPEND CMAKE_Fortran_FLAGS_DEBUG " -O0 -g -fcheck=all -fbacktrace")
  string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O3")
  set(_MRRC_FT8_TOOLCHAIN_FLAGS_APPENDED TRUE)
endif()
