"""ADIF generation regressions (NFR-072: non-void canonical records only)."""

from __future__ import annotations

import pytest

from server.engine.adif import generate_adif
from server.engine.repository import QsoStatus, StoredQSO


def stored(
    dx_call: str = "K1ABC",
    status: QsoStatus = QsoStatus.COMPLETED,
    epoch: float = 1_700_000_000.0,  # 2023-11-14T22:13:20Z
    dx_grid: str = "FN42",
    freq_hz: int = 14_074_000,
    band: str = "20m",
) -> StoredQSO:
    return StoredQSO(
        id=1,
        my_call="M0XX",
        my_grid="IO91",
        dx_call=dx_call,
        dx_grid=dx_grid,
        report_sent=-12,
        report_rcvd=-8,
        started_utc="221320",
        mode="FT8",
        freq_hz=freq_hz,
        band=band,
        status=status,
        completed_epoch=epoch,
        void_actor=None,
        void_reason=None,
    )


def test_single_record_fields_and_lengths() -> None:
    doc = generate_adif([stored()], generated_epoch=1_700_000_100.0)
    assert doc.startswith("Generated by MRRC-FT8 at 2023-11-14T22:15:00Z\n")
    assert "<ADIF_VER:5>3.1.4" in doc
    assert "<PROGRAMID:8>MRRC-FT8" in doc
    assert "<EOH>" in doc
    record = doc.split("<EOH>\n", 1)[1]
    for expected in (
        "<STATION_CALLSIGN:4>M0XX",
        "<MY_GRIDSQUARE:4>IO91",
        "<CALL:5>K1ABC",
        "<GRIDSQUARE:4>FN42",
        "<RST_SENT:3>-12",
        "<RST_RCVD:3>-08",
        "<QSO_DATE:8>20231114",
        "<TIME_ON:6>221320",
        "<MODE:3>FT8",
        "<FREQ:9>14.074000",
        "<BAND:3>20m",
    ):
        assert expected in record
    assert record.rstrip().endswith("<EOR>")


def test_void_records_are_excluded() -> None:
    doc = generate_adif(
        [stored("K1ABC"), stored("W1AW", status=QsoStatus.VOID), stored("N2YJ")],
        generated_epoch=0.0,
    )
    assert "K1ABC" in doc and "N2YJ" in doc
    assert "W1AW" not in doc
    assert doc.count("<EOR>") == 2


def test_optional_fields_omitted_when_empty() -> None:
    doc = generate_adif(
        [stored(dx_grid="", freq_hz=0, band="")], generated_epoch=0.0
    )
    assert "<GRIDSQUARE:" not in doc
    assert "<FREQ:" not in doc
    assert "<BAND:" not in doc
    assert doc.count("<EOR>") == 1


def test_aborted_restart_records_remain_exportable() -> None:
    doc = generate_adif([stored(status=QsoStatus.ABORTED_RESTART)], generated_epoch=0.0)
    assert "K1ABC" in doc  # only void rows are excluded (NFR-072)


def test_non_printable_content_is_rejected() -> None:
    bad = stored("K1ABC")
    object.__setattr__(bad, "dx_call", "K1ABC\r\n<EOR>")
    with pytest.raises(ValueError, match="non-printable"):
        generate_adif([bad], generated_epoch=0.0)


def test_empty_export_is_header_only() -> None:
    doc = generate_adif([], generated_epoch=0.0)
    assert "<EOH>" in doc
    assert "<EOR>" not in doc
