set(IMPROVED_FT8_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/patched/ft8_mod1.f90
    ${WSJTX_LIB}/ft8var/jt65_mod2var.f90
    ${WSJTX_LIB}/ft8var/jt65_mod5.f90
    ${WSJTX_LIB}/ft8var/jt65_mod9.f90
    ${CMAKE_CURRENT_SOURCE_DIR}/patched/ft8_decodevar.f90
    ${WSJTX_LIB}/ft8var/agccft8.f90
    ${WSJTX_LIB}/ft8var/baddatavar.f90
    ${WSJTX_LIB}/ft8var/bpdecode174_91var.f90
    ${WSJTX_LIB}/ft8var/chkfalse8var.f90
    ${WSJTX_LIB}/ft8var/chkflscallvar.f90
    ${WSJTX_LIB}/ft8var/chkgridvar.f90
    ${WSJTX_LIB}/ft8var/chklong8.f90
    ${WSJTX_LIB}/ft8var/chkspecial8var.f90
    ${WSJTX_LIB}/ft8var/cwfilter.f90
    ${WSJTX_LIB}/ft8var/datacor.f90
    ${CMAKE_CURRENT_SOURCE_DIR}/patched/encode174_91var.f90
    ${WSJTX_LIB}/ft8var/extract_callvar.f90
    ${WSJTX_LIB}/ft8var/filbigvar.f90
    ${WSJTX_LIB}/ft8var/fillhashvar.f90
    ${WSJTX_LIB}/ft8var/filtersfreevar.f90
    ${CMAKE_CURRENT_SOURCE_DIR}/patched/four2avar.f90
    ${CMAKE_CURRENT_SOURCE_DIR}/patched/ft8apsetvar.f90
    ${WSJTX_LIB}/ft8var/ft8bvar.f90
    ${CMAKE_CURRENT_SOURCE_DIR}/patched/ft8_downsamplevar.f90
    ${WSJTX_LIB}/ft8var/ft8mf1var.f90
    ${WSJTX_LIB}/ft8var/ft8mfcqvar.f90
    ${WSJTX_LIB}/ft8var/ft8svar.f90
    ${WSJTX_LIB}/ft8var/ft8sdvar.f90
    ${WSJTX_LIB}/ft8var/ft8sd1var.f90
    ${WSJTX_LIB}/ft8var/genft8var.f90
    ${WSJTX_LIB}/ft8var/gen_ft8wavevar.f90
    ${WSJTX_LIB}/ft8var/genft8sdvar.f90
    ${WSJTX_LIB}/ft8var/msgparservar.f90
    ${CMAKE_CURRENT_SOURCE_DIR}/patched/osd174_91var.f90
    ${WSJTX_LIB}/ft8var/packjt77sdvar.f90
    ${WSJTX_LIB}/ft8var/partint.f90
    ${WSJTX_LIB}/ft8var/partintft8.f90
    ${WSJTX_LIB}/ft8var/rms_augapvar.f90
    ${WSJTX_LIB}/ft8var/searchcallsvar.f90
    ${WSJTX_LIB}/ft8var/subtractft8var.f90
    ${WSJTX_LIB}/ft8var/sync8var.f90
    ${WSJTX_LIB}/ft8var/sync8dvar.f90
    ${WSJTX_LIB}/ft8var/tone8.f90
    ${WSJTX_LIB}/ft8var/tone8myc.f90
    ${WSJTX_LIB}/ft8var/tonesdvar.f90
    ${WSJTX_LIB}/ft8var/twkfreq1var.f90
)
